"""Add Gallery module

Revision ID: 6df616a4616a
Revises: f566c8e363cb
Create Date: 2026-04-17 13:51:48.273407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6df616a4616a'
down_revision: Union[str, None] = 'f566c8e363cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gallery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gallery_filename'), 'gallery', ['filename'], unique=True)
    op.create_index(op.f('ix_gallery_id'), 'gallery', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gallery_id'), table_name='gallery')
    op.drop_index(op.f('ix_gallery_filename'), table_name='gallery')
    op.drop_table('gallery')
    # ### end Alembic commands ###
